name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Make Envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_PROD_BOT_TOKEN: ${{ secrets.PROD_BOT_TOKEN }}
          envkey_MONGO_URL: ${{ secrets.MONGO_URL }}
          envkey_DEV_BOT_TOKEN: ${{ secrets.DEV_BOT_TOKEN }}
          envkey_WCL_API_KEY: ${{ secrets.WCL_API_KEY }}
          envkey_SHAME_MP3: ${{ secrets.SHAME_MP3 }}
          envkey_WCL_URL: ${{ secrets.WCL_URL }}
          envkey_RAIDERIO_URL: ${{ secrets.RAIDERIO_URL }}
          directory: .
          file_name: .env
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jwshive/the-ruffian-bot:production
    # steps:
    # - uses: actions/checkout@v2
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag the-ruffian-bot:$(date +%s)
